#参考サイト
#https://qiita.com/yu-ichiro/items/b50ceb0008edc3c0312e
#ワークフローの名前
name: CI

#どのタイミングでこのワークフローが走るかが定義されている。
on:
  #何かしらのコミットがGitHubに追加された時
  push:
    #ただし、mainブランチのみ
    branches: [ "main" ]
  #新しくプルリクエストが作成された時
  pull_request:
    #ただし、mainブランチのみ
    branches: [ "main" ]
  #明示的に走って！とボタンを押した時
  workflow_dispatch:
  #上記の条件分岐を必要としない場合は、以下のようにする
  #※mainブランチのみであることに注意
  #push: [ "main" ]

#一つのワークフローの中に含まれる一つ一つの一連の処理を定義する。
jobs:
  #(ジョブ名):の中にそれぞれのジョブの設定、処理内容を書く。
  #並列に処理される！
  #build:というジョブ
  build:
    #どのような仮想環境でジョブの処理を動かすかを定義
    #最新バージョンのubuntu環境を準備する。
    runs-on: ubuntu-latest

    #具体的な一つ一つの処理を書いていく。
    #上から順に実行される！
    steps:
      #各処理を記述
      #外部で定義された別のアクション
      #自分自身のレポジトリのデータを読み込む
      - uses: actions/checkout@v3

      #単一のスクリプトが走る
      - name: Run a one-line script
        run: echo Hello, world!

       #複数のスクリプトが走る
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  hogehoge:
    runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Unko
          run: echo Unko!!!
